<a href="https://colab.research.google.com/github/mehakpkaur/assignment/blob/main/assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50])
add = arr+2
print("addition : ", add)
multiply = arr*3
print("multiplication : ", multiply)
divide = arr/2
print("division : ", divide)

addition :  [12 22 32 42 52]
multiplication :  [ 30  60  90 120 150]
division :  [ 5. 10. 15. 20. 25.]


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5])
r= np.flip(arr)
print(r)

x = np.array([1,2,3,4,5,1,2,1,1,1])
mfrequent  = np.bincount(x).argmax()
print(mfrequent)

y = np.array([1,1,1,2,3,4,2,4,3,3])
m_yfrequent = np.bincount(y).argmax()
print(m_yfrequent)


[5 4 3 2 1]
1
1


In [12]:
import numpy as np
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[2][0])

20
70


In [17]:
import numpy as np
mehak = np.linspace(10,100, num = 25)
print(mehak)
#
print("dimensions :", mehak.ndim)
print("shape :", mehak.shape)
print("total elements :", mehak.size)
print("data type :", mehak.dtype)
print("total bytes :",mehak.nbytes)
#transpose
transpose_arr = mehak.reshape(25,1)
print(transpose_arr)
#no we can't do the same with T attribute


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
dimensions : 1
shape : (25,)
total elements : 25
data type : float64
total bytes : 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [29]:
import numpy as np
ucs420_mehak = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("mean: ",np.mean(ucs420_mehak))
print("median :",np.median(ucs420_mehak))
print("maximum :",np.max(ucs420_mehak))
print("minimum :",np.min(ucs420_mehak))
print("unique elements:",np.unique(ucs420_mehak))
reshaped_ucs420_mehak = ucs420_mehak.reshape(4,3)
print(reshaped_ucs420_mehak)
resized_ucs420_mehak = ucs420_mehak.resize(2,3,refcheck = False)
print(resized_ucs420_mehak)

mean:  43.333333333333336
median : 37.5
maximum : 90
minimum : 10
unique elements: [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
None
